import type { ToolDefinition } from '@/types/tool'

export const generateVideoScriptsTool: ToolDefinition = {
  id: 'generate_video_scripts',
  label: 'Generate Video Scripts',
  description:
    'Creates short, high-converting video scripts, ad copy, and headline sets for Facebook and Instagram — grounded in ICP data and brand voice. Supports B2C and B2B audiences, multiple lengths and output formats, and a reference learning system that improves output over time.',
  workflow_file: 'workflows/generate_video_scripts.md',
  output_type: 'video_scripts',
  status: 'active',
  context_needs: ['overview', 'services', 'icp'],
  saves_to: 'workflow_outputs',
  prerequisites: ['build_icp'],
  model: 'claude-sonnet-4-6',
  max_tokens: 16000,
  required_inputs: [
    {
      key: 'target_service',
      label: 'Current Offer',
      type: 'text',
      required: true,
      placeholder: 'e.g. Heat Pump Install + Mass Save Rebate',
    },
    {
      key: 'audience_type',
      label: 'Audience',
      type: 'select',
      required: true,
      options: ['B2C', 'B2B'],
    },
    {
      key: 'script_style',
      label: 'Style',
      type: 'select',
      required: true,
      options: ['UGC', 'Voice Over'],
    },
    {
      key: 'output_type',
      label: 'Output Type',
      type: 'select',
      required: true,
      options: ['videos', 'ad_copy', 'headlines'],
    },
    {
      key: 'script_goal',
      label: 'Goal',
      type: 'select',
      required: true,
      options: ['Lead Generation', 'Awareness', 'Retargeting', 'Trust Building'],
    },
    {
      key: 'script_length',
      label: 'Length',
      type: 'select',
      required: true,
      options: ['15s', '30s', '60s', '90s'],
    },
  ],
  optional_inputs: [
    {
      key: 'script_count',
      label: 'Number of Variations',
      type: 'select',
      required: false,
      options: ['1', '3', '5'],
      default_value: '3',
    },
    {
      key: 'specific_offer',
      label: 'Specific Offer (optional)',
      type: 'text',
      required: false,
      placeholder: 'e.g. Mass Save $8,500 rebate + 0% financing for 84 months',
    },
    {
      key: 'hook_angle',
      label: 'Hook Angle (optional)',
      type: 'text',
      required: false,
      placeholder: 'e.g. Focus on the homeowner who keeps delaying the replacement',
    },
    {
      key: 'notes',
      label: 'Additional Notes (optional)',
      type: 'textarea',
      required: false,
      placeholder: 'e.g. Seasonal push — summer heat. Address objection: too expensive.',
    },
    {
      key: 'include_broll_notes',
      label: 'Include B-Roll Notes',
      type: 'select',
      required: false,
      options: ['No', 'Yes'],
      default_value: 'No',
    },
  ],
}
